"""add initial datas

Revision ID: 0f29824b3a45
Revises: 17bbe55712d4
Create Date: 2023-04-24 17:18:28.726338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f29824b3a45'
down_revision = '17bbe55712d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("INSERT INTO todos (task,checked,created_at,updated_at) VALUES ('111',False,'2023-05-05 05:05:05.819812','2023-05-05 05:05:05.819812')")
    conn.execute("INSERT INTO todos (task,checked,created_at,updated_at) VALUES ('222',False,'2023-05-05 05:05:05.819812','2023-05-05 05:05:05.819812')")
    conn.execute("INSERT INTO todos (task,checked,created_at,updated_at) VALUES ('333',True,'2023-05-05 05:05:05.819812','2023-05-05 05:05:05.819812')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
