"""add checked column

Revision ID: 17bbe55712d4
Revises: 9831c8b7557b
Create Date: 2023-04-24 17:17:42.061721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17bbe55712d4'
down_revision = '9831c8b7557b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('checked', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'checked')
    # ### end Alembic commands ###
